name: setup-terraform-lint
description: Install the shared Terraform and TFLint versions.

runs:
  using: composite
  steps:
    - name: Set Up Terraform
      uses: hashicorp/setup-terraform@v4
      with:
        terraform_version: 1.15.9

    - name: Set Up TFLint
      uses: terraform-linters/setup-tflint@v6
      with:
        tflint_version: v0.64.0
