# workflows/lint-markdown.yml
#
# Lint Markdown
# Lint Markdown files using markdownlint and Prettier.

name: Lint Markdown

on:
  push:
    branches:
      - main
    paths:
      - "**/*.md"
      - "**/*.mdx"
      - ".github/workflows/lint-markdown.yml"
      - "lint-markdown/**"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**/*.md"
      - "**/*.mdx"
      - ".github/workflows/lint-markdown.yml"
      - "lint-markdown/**"
  workflow_dispatch:

concurrency:
  group: lint-markdown-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint-markdown:
    name: Lint Markdown Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v7

      - name: Lint Markdown
        uses: ./lint-markdown
        with:
          ignore-path: .prettierignore
